### ISSUE TITLE
`test/agreement` has 12/24 assertions passing. fix indexing related issues

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#253]
```
cd test
WASM_LOG=debug RUST_LOG="error,wasmer_compiler_cranelift=error,holochain::core::workflow=error,holochain::conductor::handle=error,holochain::conductor::entry_def_store=error,holochain_p2p::spawn::actor=error" RUST_BACKTRACE=1 npx tape agreement/test_agreement_links.js
```

- [x] `test_agreement_crud.js` has been updated but needs fixing the assertions or calls
- [x] `test_agreement_links.js` needs updating to new tryorama (easy)
- [x] fix indexing related issue

same or very similar as over in #246

With some added logging, we can see this now:
```
hc_zome_rea_economic_event_lib:zomes/rea_economic_event/lib/src/lib.rs:201 realization_of results: 
[
Err(NotConfigured(ZomeName("economic_event"), FunctionName("_internal_index_agreement_economic_events"))), 
Ok(RemoteEntryLinkResponse { indexes_created: [Ok(HeaderHash(0x842924919e1c7b7396d5de9fecb161950af5b020f67546d193548372377ce5daa119aadbdcd501)), Ok(HeaderHash(0x8429245d7f928a2cf8e8a86bf9780ab54a4a77756bd253d5c02682898f8019099042df9c6def64))], indexes_removed: [] }),
Err(Wasm(Host("Attempted to call a zome function that doesn't exist: Zome: agreement_index Fn index_economic_events")))
]
```

```
not ok 6 commitment ref added
  ---
    operator: equal
    expected: 1
    actual:   0
```

related code: 
https://github.com/h-REA/hREA/blob/13d4987c182fd1d7f08fa492c81e92005189b53a/test/agreement/test_agreement_links.js#L108

and 
https://github.com/h-REA/hREA/blob/13d4987c182fd1d7f08fa492c81e92005189b53a/test/agreement/test_agreement_links.js#L81-L105

**Comment by Connoropolous** [comment]
Output: 

```
18:40:55 [tryorama] info: Using the following settings from environment variables:
18:40:55 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
18:40:55 [tryorama] debug: About to execute 1 tests
18:40:55 [tryorama] debug: Executing test: Agreement record API
18:40:55 [tryorama] debug: About to execute 1 tests
18:40:55 [tryorama] debug: Executing test: Agreement links & queries
TAP version 13
# Agreement record API
18:40:55 [tryorama] debug: api.players: creating players
18:40:55 [tryorama] debug: api.players: seed args generated for c0 = {"configDir":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/eaPytQ","adminInterfacePort":33000,"scenarioName":"Agreement record API","playerName":"c0","uid":"e0225bd4-bf9c-493b-9e43-83d863c3c2ac"}
18:40:55 [tryorama] debug: built config: {"network":{"network_type":"quic_bootstrap","transport_pool":[{"type":"quic"}]},"environment_path":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/eaPytQ","keystore":{"type":"lair_server_legacy_deprecated","keystore_path":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/eaPytQ/keystore","danger_passphrase_insecure_from_config":"pass"},"admin_interfaces":[{"driver":{"type":"websocket","port":33000}}],"app_interfaces":[{"driver":{"type":"websocket","port":0}}]}
18:40:55 [tryorama] debug: api.players: player config committed for c0
18:40:55 [tryorama] debug: api.players: players built
FIXME: ignoring onJoin
18:40:55 [tryorama: player c0] debug: starting up
18:40:55 [tryorama] info: Spawning lair for test with keystore at:  /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/eaPytQ/keystore
18:40:55 [tryorama] info: Using conductor path:  holochain
18:40:55 [tryorama] info: Holochain version:     holochain 0.0.128

18:40:55 [tryorama] info: Conductor config path: /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/eaPytQ/conductor-config.yml
18:40:55 [tryorama] debug: running: holochain -c /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/eaPytQ/conductor-config.yml
18:40:55 info:
☉☉☉ [[[CONDUCTOR c0]]]
☉
☉ ###HOLOCHAIN_SETUP###
☉ ###ADMIN_PORT:33000###
☉ ###HOLOCHAIN_SETUP_END###
☉ Conductor ready.
☉
18:40:55 [tryorama] info: Conductor 'c0' process spawning completed.
18:40:55 [tryorama: tryorama conductor c0] debug: Conductor constructing
18:40:55 [tryorama: player c0] debug: started up
18:40:55 [tryorama: player c0] debug: initializing
18:40:55 [tryorama: tryorama conductor c0] debug: connectInterfaces :: connected admin interface at ws://localhost:33000
App Port spun up on port  52174
18:40:55 [tryorama: tryorama conductor c0] debug: connectInterfaces :: connected app interface at ws://localhost:52174
18:40:55 [tryorama: player c0] debug: initialized
18:40:55 [tryorama: player c0] debug: Player.installHapps
18:40:55 [tryorama: player c0] debug: Player.adminWs()
18:40:55 [tryorama: player c0] debug: Player.installHapp(["/Users/connor/code/hrea/bundles/dna/agreement/hrea_agreement.dna"], noAgentPubKey)
18:40:57 [tryorama: player c0] debug: Player.adminWs()
18:40:57 [tryorama: player c0] debug: Player.appWs()
Init Holochain connection: ws://localhost:52174
Holochain connection to ws://localhost:52174 OK
GraphQL query error Error: Unexpected error value: { type: "error", data: { type: "ribosome_error", data: "Wasm error while working with Ribosome: Guest(\"Error in remote call Local zome call failed: agreement zome is not configured for target _internal_read_agreement_commitments\")" } }
    at locatedError (/Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/error/locatedError.js:23:78)
    at /Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/execution/execute.js:479:52
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.graphQL (/Users/connor/code/hrea/test/init.js:72:20)
    at /Users/connor/code/hrea/test/agreement/test_agreement_crud.js:25:20
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  locations: [ { line: 3, column: 7 } ],
  path: [ 'res' ]
}
18:40:57 [tryorama] error: Test error: "TypeError: Cannot read properties of null (reading 'res')\n" +
  '    at /Users/connor/code/hrea/test/agreement/test_agreement_crud.js:38:24\n' +
  '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
          at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
          at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
  ...
18:40:57 [tryorama] debug: Test failed: Agreement record API TypeError: Cannot read properties of null (reading 'res')
    at /Users/connor/code/hrea/test/agreement/test_agreement_crud.js:38:24
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  [stack]: "TypeError: Cannot read properties of null (reading 'res')\n" +
    '    at /Users/connor/code/hrea/test/agreement/test_agreement_crud.js:38:24\n' +
    '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)',
  [message]: "Cannot read properties of null (reading 'res')"
}
18:40:57 [tryorama] debug: Cleaning up test: Agreement record API
18:40:57 [tryorama] debug: Calling Api._cleanup. description: Agreement record API
18:40:57 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
18:40:57 [tryorama: player c0] debug: Shutting down...
# Agreement links & queries
18:40:57 [tryorama] debug: api.players: creating players
18:40:57 [tryorama] error: Test error: 'Error: Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.\n' +
  '    at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:56:15\n' +
  '    at Array.forEach (<anonymous>)\n' +
  '    at ScenarioApi.players (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:54:19)\n' +
  '    at buildPlayer (/Users/connor/code/hrea/test/init.js:90:35)\n' +
  '    at /Users/connor/code/hrea/test/agreement/test_agreement_links.js:28:23\n' +
  '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:35)\n' +
  '    at Test.<anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:127:7)\n' +
  '    at Test.bound [as _cb] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)\n' +
  '    at Test.run (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:106:10)\n' +
  '    at Test.bound [as run] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)'
not ok 2 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
          at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
          at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at runNextTicks (node:internal/process/task_queues:65:3)
          at processImmediate (node:internal/timers:437:9)
  ...
18:40:57 [tryorama] debug: Test failed: Agreement links & queries Error: Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.
    at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:56:15
    at Array.forEach (<anonymous>)
    at ScenarioApi.players (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:54:19)
    at buildPlayer (/Users/connor/code/hrea/test/init.js:90:35)
    at /Users/connor/code/hrea/test/agreement/test_agreement_links.js:28:23
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:35)
    at Test.<anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:127:7)
    at Test.bound [as _cb] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
    at Test.run (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:106:10)
    at Test.bound [as run] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32) {
  [stack]: 'Error: Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.\n' +
    '    at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:56:15\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at ScenarioApi.players (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:54:19)\n' +
    '    at buildPlayer (/Users/connor/code/hrea/test/init.js:90:35)\n' +
    '    at /Users/connor/code/hrea/test/agreement/test_agreement_links.js:28:23\n' +
    '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:35)\n' +
    '    at Test.<anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:127:7)\n' +
    '    at Test.bound [as _cb] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)\n' +
    '    at Test.run (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:106:10)\n' +
    '    at Test.bound [as run] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)',
  [message]: 'Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.'
}
18:40:57 [tryorama] debug: Cleaning up test: Agreement links & queries
18:40:57 [tryorama] debug: Calling Api._cleanup. description: Agreement links & queries
18:40:57 [tryorama] debug: Finished with test: Agreement links & queries
18:40:57 [tryorama: tryorama conductor c0] debug: Killing...
18:40:57 [tryorama] info: conductor 'c0' exited with code null
18:40:57 [tryorama: player c0] debug: Shut down.
FIXME: ignoring onLeave
18:40:57 [tryorama] debug: Finished with test: Agreement record API

1..2
# tests 2
# pass  0
# fail  2
```

**Comment by Connoropolous** [comment]
@pospi in terms of solving the first issue here, which seems to relate to indexing, can you expand on this 'TODO' here?
https://github.com/h-REA/hREA/blob/9bdcaf129046099bca0c6e3d995bcab0c819d041/zomes/rea_agreement/zome_idx_agreement/src/lib.rs#L4

What is the TODO? Was this zome or configuration not updated during some previous pass? Is it different than others?

**Comment by pospi** [comment]
I had a bit of a check for things, seems like it could be missing some declarations.

One is more about [this issue](https://github.com/h-REA/hREA/blob/57681b2/zomes/rea_economic_resource/zome_idx_observation/src/lib.rs#L14)- I don't feel as though I should have to be declaring that extern, that but if it's expected zome developer experience then we can remove the TODO and add these to all index zome crates.
I also don't think I should need to be defining `PathEntry` as an `EntryDef` for the zome because I'm not using Paths anywhere in my indexing lib anymore :/

Another TODO *would* have been adding indexes against `Agent` (which aren't declared yet), but it looks like `involvedAgents` is a [derived field](https://www.valueflo.ws/specification/inverses/#agreement). So let's leave that one for now- it will likely be interesting to implement since we haven't done any of them yet.

**Comment by fosterlynn** [comment]
>it looks like involvedAgents is a [derived field](https://www.valueflo.ws/specification/inverses/#agreement)

correct, just a query

**Comment by Connoropolous** [comment]
after seeing an error like this:
```
GraphQL query error GraphQLError [Object]: ID cannot represent value: <Buffer 84 29 24 2a 48 45 04 a7 a7 74 4c 3a cb ef fa 58 72 3d ef f0 d2 8f 52 12 d8 23 e3 e3 3d e3 bd 1d df 82 1e bb 62 80 ce>
    at GraphQLScalarType.serializeID [as serialize]
```

occur on an object like this: 
```
{
  agreement: {
    id: 'uhCEkp124_GIEwnLZ4s0CuHLqhosYmWLJ0zflSSgXAfbZ3YZJO4C7:uhC0k1v0fhEyKMek-MkZ0fxKP9s3LKkShPyNgOMhaak28c3BumFfO',
    revisionId: <Buffer 84 29 24 2a 48 45 04 a7 a7 74 4c 3a cb ef fa 58 72 3d ef f0 d2 8f 52 12 d8 23 e3 e3 3d e3 bd 1d df 82 1e bb 62 80 ce>,
    name: 'test agreement',
    created: 2022-04-25T16:14:26.386Z,
    note: 'just testing, nothing was rly agreed'
  }
}
```

I realized that `revisionId` wasn't getting caught by the client side (de)serializing code. I fixed that here: https://github.com/h-REA/hREA/commit/f17bc767ad915acb8856f80243201d69b56d8d38
and that fixed that particular set of tests within agreement :)

interestingly, the tests that were passing, such as test/economic_resources were passing because they don't use the Graphql layer within the tests, they use raw zome calls and therefore had no issues handling in the raw Uint8Array revisionId's

Now for this ticket we only have left to update the file `test_agreement_links.js` to new tryorama (easy)

**Comment by Connoropolous** [comment]
Now that I've updated tryorama in https://github.com/h-REA/hREA/commit/13d4987c182fd1d7f08fa492c81e92005189b53a, we are in fact back to the issue of indexing. That is the last piece

**Comment by Connoropolous** [comment]
@pospi I've gotten it to a place where I see this. 

There is no inclusion of any zome that would handle agreement_index for the Observation DNA

hc_zome_rea_economic_event_lib:zomes/rea_economic_event/lib/src/lib.rs:201 realization_of results: 
[
Err(NotConfigured(ZomeName("economic_event"), FunctionName("_internal_index_agreement_economic_events"))), 
Ok(RemoteEntryLinkResponse { indexes_created: [Ok(HeaderHash(0x842924919e1c7b7396d5de9fecb161950af5b020f67546d193548372377ce5daa119aadbdcd501)), Ok(HeaderHash(0x8429245d7f928a2cf8e8a86bf9780ab54a4a77756bd253d5c02682898f8019099042df9c6def64))], indexes_removed: [] }),
Err(Wasm(Host("Attempted to call a zome function that doesn't exist: Zome: agreement_index Fn index_economic_events")))
]

**Comment by pospi** [comment]
Completed via https://github.com/h-REA/hREA/issues/263#issuecomment-1109312721

**Comment by pospi** [comment]
Nice! Does this mean a `RevisionId` / `HeaderHash` now looks string-like when accessed / debugged via the GraphQL API?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Connoropolous** [comment]
> Nice! Does this mean a `RevisionId` / `HeaderHash` now looks string-like when accessed / debugged via the GraphQL API?

Yep
