### ISSUE TITLE
`test/flows` has 37/40(?) assertions passing. Fix indexing related issue

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#254]
- [x] fix indexing related issue

Could be related to this change in this commit:
https://github.com/h-REA/hREA/commit/79a5bebefe13488b7afb2f7a1250b53907203375#diff-416d45b2d9d21f7728677a5b6c04799b0cd94cb8bc7acbd23758a2b9ffc87040

to test, run:
```
cd test
WASM_LOG=debug RUST_LOG="error,wasm_trace=debug" RUST_BACKTRACE=1 npx tape flows/**/*.js
```

pass  37
fail  3

Core error: 
```
hc_zome_rea_fulfillment_lib_destination:
zomes/rea_fulfillment/lib_destination/src/lib.rs:39
handle_create_fulfillment::fulfilled_by::create_index!:
[
  Ok(RemoteEntryLinkResponse { indexes_created: [Ok(HeaderHash(0x84292407ff025da821002a5e9f3a088436da7c2bda35b9833963f9568d91d5f2758a719d7f94bf)), Ok(HeaderHash(0x8429249eb37aafcde9867047370f732e31daa9f6c0777f836f9f3ab93cdbf5bf30154182b185bd))], indexes_removed: [] }),
  Err(Wasm(Host("Attempted to call a zome function that doesn't exist: Zome: economic_event_index Fn _internal_index_event_fulfills")))]
}
```

related code:

**Comment by Connoropolous** [comment]
Output: 

```
18:34:43 [tryorama] info: Using the following settings from environment variables:
18:34:43 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
18:34:43 [tryorama] debug: About to execute 1 tests
18:34:43 [tryorama] debug: Executing test: flow records and relationships
TAP version 13
# flow records and relationships
18:34:43 [tryorama] debug: api.players: creating players
18:34:43 [tryorama] debug: api.players: seed args generated for c0 = {"configDir":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/IWvweF","adminInterfacePort":33000,"scenarioName":"flow records and relationships","playerName":"c0","uid":"243cae99-97cd-4608-a573-77c83d875d46"}
18:34:43 [tryorama] debug: built config: {"network":{"network_type":"quic_bootstrap","transport_pool":[{"type":"quic"}]},"environment_path":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/IWvweF","keystore":{"type":"lair_server_legacy_deprecated","keystore_path":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/IWvweF/keystore","danger_passphrase_insecure_from_config":"pass"},"admin_interfaces":[{"driver":{"type":"websocket","port":33000}}],"app_interfaces":[{"driver":{"type":"websocket","port":0}}]}
18:34:43 [tryorama] debug: api.players: player config committed for c0
18:34:43 [tryorama] debug: api.players: players built
FIXME: ignoring onJoin
18:34:43 [tryorama: player c0] debug: starting up
18:34:43 [tryorama] info: Spawning lair for test with keystore at:  /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/IWvweF/keystore
18:34:43 [tryorama] info: Using conductor path:  holochain
18:34:43 [tryorama] info: Holochain version:     holochain 0.0.128

18:34:43 [tryorama] info: Conductor config path: /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/IWvweF/conductor-config.yml
18:34:43 [tryorama] debug: running: holochain -c /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/IWvweF/conductor-config.yml
18:34:43 info:
☉☉☉ [[[CONDUCTOR c0]]]
☉
☉ ###HOLOCHAIN_SETUP###
☉ ###ADMIN_PORT:33000###
☉ ###HOLOCHAIN_SETUP_END###
☉ Conductor ready.
☉
18:34:43 [tryorama] info: Conductor 'c0' process spawning completed.
18:34:43 [tryorama: tryorama conductor c0] debug: Conductor constructing
18:34:43 [tryorama: player c0] debug: started up
18:34:43 [tryorama: player c0] debug: initializing
18:34:43 [tryorama: tryorama conductor c0] debug: connectInterfaces :: connected admin interface at ws://localhost:33000
App Port spun up on port  52118
18:34:43 [tryorama: tryorama conductor c0] debug: connectInterfaces :: connected app interface at ws://localhost:52118
18:34:43 [tryorama: player c0] debug: initialized
18:34:43 [tryorama: player c0] debug: Player.installHapps
18:34:43 [tryorama: player c0] debug: Player.adminWs()
18:34:43 [tryorama: player c0] debug: Player.installHapp(["/Users/connor/code/hrea/bundles/dna/observation/hrea_observation.dna","/Users/connor/code/hrea/bundles/dna/planning/hrea_planning.dna"], noAgentPubKey)
18:34:55 [tryorama: player c0] debug: Player.adminWs()
18:34:55 [tryorama: player c0] debug: Player.appWs()
Init Holochain connection: ws://localhost:52118
Holochain connection to ws://localhost:52118 OK
ok 1 process created OK
18:34:57 info:
★★★ [[[CONDUCTOR c0]]]
★ Apr 12 18:34:57.062 ERROR wasm_trace: hc_zome_rea_commitment::__create_commitment_extern:zomes/rea_commitment/zome/src/lib.rs:74 output_type = "core::result::Result<hc_zome_rea_commitment_rpc::ResponseData, holochain_wasmer_common::result::WasmError>"; bytes = [129, 170, 99, 111, 109, 109, 105, 116, 109, 101, 110, 116, 136, 166, 97, 99, 116, 105, 111, 110, 167, 99, 111, 110, 115, 117, 109, 101, 167, 105, 110, 112, 117, 116, 79, 102, 146, 196, 39, 132, 45, 36, 216, 190, 143, 23, 200, 150, 183, 5, 10, 107, 3, 11, 17, 160, 238, 15, 86, 3, 239, 104, 87, 254, 4, 39, 127, 23, 207, 199, 178, 248, 132, 67, 42, 124, 111, 250, 196, 39, 132, 33, 36, 249, 84, 242, 200, 112, 251, 203, 78, 242, 120, 121, 28, 27, 16, 35, 70, 147, 15, 28, 108, 139, 70, 181, 240, 241, 144, 142, 154, 249, 71, 96, 0, 51, 49, 142, 237, 180, 114, 101, 115, 111, 117, 114, 99, 101, 67, 108, 97, 115, 115, 105, 102, 105, 101, 100, 65, 115, 145, 178, 115, 111, 109, 101, 45, 114, 101, 115, 111, 117, 114, 99, 101, 45, 116, 121, 112, 101, 176, 114, 101, 115, 111, 117, 114, 99, 101, 81, 117, 97, 110, 116, 105, 116, 121, 130, 177, 104, 97, 115, 78, 117, 109, 101, 114, 105, 99, 97, 108, 86, 97, 108, 117, 101, 1, 167, 104, 97, 115, 85, 110, 105, 116, 177, 116, 111, 100, 111, 45, 115, 111, 109, 101, 45, 117, 110, 105, 116, 45, 105, 100, 163, 100, 117, 101, 189, 50, 48, 49, 57, 45, 49, 49, 45, 49, 56, 84, 50, 48, 58, 50, 57, 58, 53, 53, 46, 48, 53, 54, 45, 48, 56, 58, 48, 48, 164, 110, 111, 116, 101, 187, 115, 111, 109, 101, 32, 105, 110, 112, 117, 116, 32, 119, 105, 108, 108, 32, 98, 101, 32, 112, 114, 111, 118, 105, 100, 101, 100, 168, 112, 114, 111, 118, 105, 100, 101, 114, 146, 196, 39, 132, 45, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 196, 39, 132, 32, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 114, 101, 99, 101, 105, 118, 101, 114, 146, 196, 39, 132, 45, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 196, 39, 132, 32, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]; Deserialize("invalid type: string \"todo-some-unit-id\", expected tuple struct UnitId")
★
GraphQL query error Error: Unexpected error value: { type: "error", data: { type: "ribosome_error", data: "Wasm error while working with Ribosome: Deserialize([129, 170, 99, 111, 109, 109, 105, 116, 109, 101, 110, 116, 136, 166, 97, 99, 116, 105, 111, 110, 167, 99, 111, 110, 115, 117, 109, 101, 167, 105, 110, 112, 117, 116, 79, 102, 146, 196, 39, 132, 45, 36, 216, 190, 143, 23, 200, 150, 183, 5, 10, 107, 3, 11, 17, 160, 238, 15, 86, 3, 239, 104, 87, 254, 4, 39, 127, 23, 207, 199, 178, 248, 132, 67, 42, 124, 111, 250, 196, 39, 132, 33, 36, 249, 84, 242, 200, 112, 251, 203, 78, 242, 120, 121, 28, 27, 16, 35, 70, 147, 15, 28, 108, 139, 70, 181, 240, 241, 144, 142, 154, 249, 71, 96, 0, 51, 49, 142, 237, 180, 114, 101, 115, 111, 117, 114, 99, 101, 67, 108, 97, 115, 115, 105, 102, 105, 101, 100, 65, 115, 145, 178, 115, 111, 109, 101, 45, 114, 101, 115, 111, 117, 114, 99, 101, 45, 116, 121, 112, 101, 176, 114, 101, 115, 111, 117, 114, 99, 101, 81, 117, 97, 110, 116, 105, 116, 121, 130, 177, 104, 97, 115, 78, 117, 109, 101, 114, 105, 99, 97, 108, 86, 97, 108, 117, 101, 1, 167, 104, 97, 115, 85, 110, 105, 116, 177, 116, 111, 100, 111, 45, 115, 111, 109, 101, 45, 117, 110, 105, 116, 45, 105, 100, 163, 100, 117, 101, 189, 50, 48, 49, 57, 45, 49, 49, 45, 49, 56, 84, 50, 48, 58, 50, 57, 58, 53, 53, 46, 48, 53, 54, 45, 48, 56, 58, 48, 48, 164, 110, 111, 116, 101, 187, 115, 111, 109, 101, 32, 105, 110, 112, 117, 116, 32, 119, 105, 108, 108, 32, 98, 101, 32, 112, 114, 111, 118, 105, 100, 101, 100, 168, 112, 114, 111, 118, 105, 100, 101, 114, 146, 196, 39, 132, 45, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 196, 39, 132, 32, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 114, 101, 99, 101, 105, 118, 101, 114, 146, 196, 39, 132, 45, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 196, 39, 132, 32, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])" } }
    at locatedError (/Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/error/locatedError.js:23:78)
    at /Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/execution/execute.js:479:52
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/connor/code/hrea/test/init.js:72:20
    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:36:17
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  locations: [ { line: 15, column: 7 } ],
  path: [ 'inputCommitment' ]
}
18:34:57 [tryorama] error: Test error: "TypeError: Cannot read properties of null (reading 'inputIntent')\n" +
  '    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:132:19\n' +
  '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)'
not ok 2 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
          at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
          at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
  ...
18:34:57 [tryorama] debug: Test failed: flow records and relationships TypeError: Cannot read properties of null (reading 'inputIntent')
    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:132:19
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  [stack]: "TypeError: Cannot read properties of null (reading 'inputIntent')\n" +
    '    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:132:19\n' +
    '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)',
  [message]: "Cannot read properties of null (reading 'inputIntent')"
}
18:34:57 [tryorama] debug: Cleaning up test: flow records and relationships
18:34:57 [tryorama] debug: Calling Api._cleanup. description: flow records and relationships
18:34:57 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
18:34:57 [tryorama: player c0] debug: Shutting down...
18:34:57 [tryorama: tryorama conductor c0] debug: Killing...
18:34:57 [tryorama] info: conductor 'c0' exited with code null
18:34:57 [tryorama: player c0] debug: Shut down.
FIXME: ignoring onLeave
18:34:57 [tryorama] debug: Finished with test: flow records and relationships

1..2
# tests 2
# pass  1
# fail  1
```

**Comment by Connoropolous** [comment]
@pospi I have updated this issue with new context about the non-trivial issues affecting this test file. 

I spent at least an hour looking into where the logic is breaking down, but without knowledge relating the cross dna indexing I feel too disadvantaged to figure it out efficiently. Can you give me some background, or advise me on this?

**Comment by Connoropolous** [comment]
It seems like the inverse of #246 , and maybe fixing the two are related

**Comment by pospi** [comment]
RE https://github.com/h-REA/hREA/issues/254#issuecomment-1107673826 see #263 :)

**Comment by pospi** [comment]
The remaining errors here seemed to be related to #266. I've implemented an ID translation mechanism which seems to be functioning well in the interim and might be acceptable long-term, see d5025681 and 7194171d.

There are still just a few failing assertions right at the end of the test. `ies` and `ics` seem to be being returned as `null` for some reason, probably due to mismatched CellIds in those queries but I'm not 100% sure. There are also some errors about `Satisfaction.satisfiedBy` being returned empty so it might actually be to do with the internals of those resolvers earlier in the test.

**Comment by pospi** [comment]
Fixed with final updates to paginated response formats
