### ISSUE TITLE
`test/satisfaction` has 17/21(?) assertions passing. Fix indexing related issue

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#255]
- [x] fix indexing related issue

It seems as if the indexing of satisfactions is happening in an unexpected DNA. I (Connor) don't understand this well enough, especially with satisfactions to fix it. The entry hash portion of the identifier is right, but the DNA half is wrong.

To work on this, run
```
cd test
WASM_LOG=debug RUST_LOG="debug,holochain::conductor::api::api_external::app_interface=error,wasmer_compiler_cranelift=error,holochain::core::workflow=error,holochain::conductor::handle=error,holochain::conductor::entry_def_store=error,holochain_p2p::spawn::actor=error" RUST_BACKTRACE=1 npx tape satisfaction/**/*.js | npx tap-dot
```

```
17 passed
4 failed

  Failed Tests:   There were 4 failures

    x EconomicEvent.satisfies reference OK
    x Satisfaction.satisfiedBy indexed correctly
    x indexing satisfactions for event query OK
    x Test threw an exception. See output for details.
```

First error: 
```
  ---
    operator: deepEqual
    expected: |-
      [
        <Buffer 84 2d 24 e0 6c 95 ef c8 4a 5f b6 29 3c 89 5e 39 5a 06 07 9f 4e ec 38 63 e0 bf 0f 59 02 61 f8 49 6c e0 e2 2b 5f 2d 78>,
        <Buffer 84 21 24 50 45 65 8a 84 e8 0e d8 16 bc 9b 63 e7 82 30 00 53 c7 91 d2 2c 7e ae 79 cc 12 1d 81 b4 54 f8 d3 07 aa c8 e9>
      ]
    actual: |-
      [
        <Buffer 84 2d 24 a5 ed f5 92 24 c5 ed bc ce 60 e7 6a 43 56 8b d3 71 e3 ba 81 71 56 70 75 21 f6 45 32 7e 8f 7c 9d 05 69 89 9f>,
        <Buffer 84 21 24 50 45 65 8a 84 e8 0e d8 16 bc 9b 63 e7 82 30 00 53 c7 91 d2 2c 7e ae 79 cc 12 1d 81 b4 54 f8 d3 07 aa c8 e9>
     ]
    at: <anonymous> (/Users/x/code/hrea/test/satisfaction/satisfaction_records_e2e.js:71:5)
    stack: |-
           Error: EconomicEvent.satisfies reference OK
```

**Comment by Connoropolous** [comment]
Output: 

```
18:20:11 [tryorama] info: Using the following settings from environment variables:
18:20:11 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
18:20:11 [tryorama] debug: About to execute 1 tests
18:20:11 [tryorama] debug: Executing test: satisfactions can be written and read between DNAs by all parties requiring access
TAP version 13
# satisfactions can be written and read between DNAs by all parties requiring access
18:20:11 [tryorama] debug: api.players: creating players
18:20:11 [tryorama] debug: api.players: seed args generated for c0 = {"configDir":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/ozwjsp","adminInterfacePort":33000,"scenarioName":"satisfactions can be written and read between DNAs by all parties requiring access","playerName":"c0","uid":"1064fd6c-74bd-4c8e-9e43-7ce82d877a39"}
18:20:11 [tryorama] debug: built config: {"network":{"network_type":"quic_bootstrap","transport_pool":[{"type":"quic"}]},"environment_path":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/ozwjsp","keystore":{"type":"lair_server_legacy_deprecated","keystore_path":"/var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/ozwjsp/keystore","danger_passphrase_insecure_from_config":"pass"},"admin_interfaces":[{"driver":{"type":"websocket","port":33000}}],"app_interfaces":[{"driver":{"type":"websocket","port":0}}]}
18:20:11 [tryorama] debug: api.players: player config committed for c0
18:20:11 [tryorama] debug: api.players: players built
FIXME: ignoring onJoin
18:20:11 [tryorama: player c0] debug: starting up
18:20:11 [tryorama] info: Spawning lair for test with keystore at:  /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/ozwjsp/keystore
18:20:11 [tryorama] info: Using conductor path:  holochain
18:20:11 [tryorama] info: Holochain version:     holochain 0.0.128

18:20:11 [tryorama] info: Conductor config path: /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/ozwjsp/conductor-config.yml
18:20:11 [tryorama] debug: running: holochain -c /var/folders/5s/rldbq43s2yj4v5xb89bwygv80000gn/T/tryorama/ozwjsp/conductor-config.yml
18:20:11 info:
☉☉☉ [[[CONDUCTOR c0]]]
☉
☉ ###HOLOCHAIN_SETUP###
☉ ###ADMIN_PORT:33000###
☉ ###HOLOCHAIN_SETUP_END###
☉ Conductor ready.
☉
18:20:11 [tryorama] info: Conductor 'c0' process spawning completed.
18:20:11 [tryorama: tryorama conductor c0] debug: Conductor constructing
18:20:11 [tryorama: player c0] debug: started up
18:20:11 [tryorama: player c0] debug: initializing
18:20:11 [tryorama: tryorama conductor c0] debug: connectInterfaces :: connected admin interface at ws://localhost:33000
App Port spun up on port  51935
18:20:11 [tryorama: tryorama conductor c0] debug: connectInterfaces :: connected app interface at ws://localhost:51935
18:20:11 [tryorama: player c0] debug: initialized
18:20:11 [tryorama: player c0] debug: Player.installHapps
18:20:11 [tryorama: player c0] debug: Player.adminWs()
18:20:11 [tryorama: player c0] debug: Player.installHapp(["/Users/connor/code/hrea/bundles/dna/planning/hrea_planning.dna","/Users/connor/code/hrea/bundles/dna/observation/hrea_observation.dna"], noAgentPubKey)
18:20:23 [tryorama: player c0] debug: Player.adminWs()
18:20:23 [tryorama: player c0] debug: Player.appWs()
Init Holochain connection: ws://localhost:51935
Holochain connection to ws://localhost:51935 OK
18:20:24 [tryorama: player c0] debug: cell.call()
ok 1 intent created successfully
18:20:24 [tryorama: player c0] debug: cell.call()
ok 2 event created successfully
18:20:24 [tryorama: player c0] debug: cell.call()
18:20:24 [tryorama] error: Test error: {
  type: 'error',
  data: {
    type: 'ribosome_error',
    data: `Wasm error while working with Ribosome: Guest("Error in remote call Host(\\"An error with entry defs in zome 'satisfaction': entry def not found for App(\\\\\\"dna_authed_method_mapping\\\\\\")\\")")`
  }
}
not ok 3 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
          at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
          at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ...
18:20:24 [tryorama] debug: Test failed: satisfactions can be written and read between DNAs by all parties requiring access {
  type: 'error',
  data: {
    type: 'ribosome_error',
    data: `Wasm error while working with Ribosome: Guest("Error in remote call Host(\\"An error with entry defs in zome 'satisfaction': entry def not found for App(\\\\\\"dna_authed_method_mapping\\\\\\")\\")")`
  }
}
18:20:24 [tryorama] debug: Cleaning up test: satisfactions can be written and read between DNAs by all parties requiring access
18:20:24 [tryorama] debug: Calling Api._cleanup. description: satisfactions can be written and read between DNAs by all parties requiring access
18:20:24 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
18:20:24 [tryorama: player c0] debug: Shutting down...
18:20:24 [tryorama: tryorama conductor c0] debug: Killing...
18:20:25 [tryorama] info: conductor 'c0' exited with code null
18:20:25 [tryorama: player c0] debug: Shut down.
FIXME: ignoring onLeave
18:20:25 [tryorama] debug: Finished with test: satisfactions can be written and read between DNAs by all parties requiring access

1..3
# tests 3
# pass  2
# fail  1
```

**Comment by Connoropolous** [comment]
found out that this relates to this here: https://github.com/holochain-open-dev/dna-auth-resolver/blob/07d3bc5287b8334c18b004ab4e1a073f5d2e0dd3/README.md#troubleshooting

since that's in use under the hood. At first I was wondering how we were getting an error 'dna_authed_method_mapping' whose text didn't appear in this source code at all, but then I remembered the underlying libraries

**Comment by Connoropolous** [comment]
I have fixed the first errors. The new error, while calling `create_satisfaction` is this: 

```
DEBUG holochain::conductor::api::api_external::app_interface: app response: Error(RibosomeError("Wasm error while working with Ribosome: Guest(\"Error in remote call Deserialize(\\\"invalid type: map, expected unit\\\")\")"))
☉
17:13:43 [tryorama] error: Test error: {
  type: 'error',
  data: {
    type: 'ribosome_error',
    data: 'Wasm error while working with Ribosome: Guest("Error in remote call Deserialize(\\"invalid type: map, expected unit\\")")'
  }
}
```

**Comment by Connoropolous** [comment]
@pospi any basic recognition of such an error?

**Comment by Connoropolous** [comment]
I figured it out: 
before
```
call_zome_method(
          event_or_commitment,
          &REPLICATE_CREATE_API_METHOD,
          CreateParams { satisfaction: satisfaction.to_owned() },
 )?;
```

after
```
// we assign a type to the response so that call_zome_method can
// effectively deserialize the response without failing
        let _result: ResponseData = call_zome_method(
          event_or_commitment,
          &REPLICATE_CREATE_API_METHOD,
          CreateParams { satisfaction: satisfaction.to_owned() },
         )?;
```

without assigning a response type, it seems that call_zome_method assumes it is trying to deserialize into the Unit type () but failing to do that when it receives non-null data

**Comment by Connoropolous** [comment]
I've updated the original issue description with the latest work to do here

**Comment by Connoropolous** [comment]
@pospi I updated this one's description with the latest. Broadly, fixing this would entail fixing configuration of satisfaction indexing I think. Can you take over?

**Comment by pospi** [comment]
Completed in 0fd25502
