### ISSUE TITLE
`test/social-architectures` has 0/? assertions passing. disable for now

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#256]
```
cd test
WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=1 npx tape social-architectures/**/*.js
```

Assessment: needs updating to new tryorama

**Comment by Connoropolous** [comment]
Output:

```
18:13:01 [tryorama] info: Using the following settings from environment variables:
18:13:01 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
18:13:01 [tryorama] debug: About to execute 1 tests
18:13:01 [tryorama] debug: Executing test: Cross-border trade scenario
TAP version 13
# Cross-border trade scenario
18:13:01 [tryorama] debug: api.players: creating players
18:13:02 [tryorama] error: Test error: 'Error: Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.\n' +
  '    at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:56:15\n' +
  '    at Array.forEach (<anonymous>)\n' +
  '    at ScenarioApi.players (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:54:19)\n' +
  '    at buildPlayer (/Users/connor/code/hrea/test/init.js:90:35)\n' +
  '    at /Users/connor/code/hrea/test/social-architectures/cross_border_trade.js:88:26\n' +
  '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:35)\n' +
  '    at Test.<anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:127:7)\n' +
  '    at Test.bound [as _cb] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)\n' +
  '    at Test.run (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:106:10)\n' +
  '    at Test.bound [as run] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
          at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
          at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ...
18:13:02 [tryorama] debug: Test failed: Cross-border trade scenario Error: Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.
    at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:56:15
    at Array.forEach (<anonymous>)
    at ScenarioApi.players (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:54:19)
    at buildPlayer (/Users/connor/code/hrea/test/init.js:90:35)
    at /Users/connor/code/hrea/test/social-architectures/cross_border_trade.js:88:26
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:35)
    at Test.<anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:127:7)
    at Test.bound [as _cb] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
    at Test.run (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:106:10)
    at Test.bound [as run] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32) {
  [stack]: 'Error: Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.\n' +
    '    at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:56:15\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at ScenarioApi.players (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/api.ts:54:19)\n' +
    '    at buildPlayer (/Users/connor/code/hrea/test/init.js:90:35)\n' +
    '    at /Users/connor/code/hrea/test/social-architectures/cross_border_trade.js:88:26\n' +
    '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:35)\n' +
    '    at Test.<anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:127:7)\n' +
    '    at Test.bound [as _cb] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)\n' +
    '    at Test.run (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:106:10)\n' +
    '    at Test.bound [as run] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)',
  [message]: 'Config for player at index 0 contains something other than a function. Either use Config.gen to create a seed function, or supply one manually.'
}
18:13:02 [tryorama] debug: Cleaning up test: Cross-border trade scenario
18:13:02 [tryorama] debug: Calling Api._cleanup. description: Cross-border trade scenario
18:13:02 [tryorama] debug: Finished with test: Cross-border trade scenario

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by pospi** [comment]
This test is kindof a stub and deals with a lot of the lesser-used Tryorama moving parts, so I think we should leave redoing it until the next version releases so we don't have to adjust for API changes.

It would also be good to run an HiA session on this test and walk through implementing it as a group- I think there's a lot of fertile ground for getting folks to think in multiparty, cross-membrane ways.

**Comment by Connoropolous** [comment]
Cool, ok noted. I am closing the issue for now, and will be effectively disabling the test for now
