### ISSUE TITLE
integration test usability, round 2

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#271]
we are still having issues with usability of the test suite. 

when the stack trace fails to include the file name, or line numbers, we don't know specifically which test in the test suite failed, and may end up wasting a lot of time just trying to figure out which test that is that is failing.

**Comment by Connoropolous** [comment]
In the original, basic `pnpm run test:integration`, when I saw a failing error, I saw:
```
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
           Error: Test threw an exception. See output for details.
             at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
             at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
             at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
             at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
             at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
             at processTicksAndRejections (node:internal/process/task_queues:96:5)

  ...



  32 tests
  438 passed
  1 failed

  Failed Tests:   There was 1 failure

    x Test threw an exception. See output for details.

 ELIFECYCLE  Command failed with exit code 1.
```


In order to figure out which test was failing, I ran the tests without the `tap-dot` filter, by running

`WASM_LOG=debug RUST_LOG="debug,wasmer_compiler_cranelift=error,holochain::core::workflow=error," RUST_BACKTRACE=1 GRAPHQL_DEBUG=1 npx tape --ignore .skip_tests **/*.js`

this gave me more useful error reporting. I did a search for 'not ok' to find the failing assertion. I discovered the test file it was occurring within: `flows/flow_records_graphql.js`. Now I could run it again just on that test file:
`WASM_LOG=debug RUST_LOG="debug,wasmer_compiler_cranelift=error,holochain::core::workflow=error," RUST_BACKTRACE=1 GRAPHQL_DEBUG=1 npx tape --ignore .skip_tests flows/flow_records_graphql.js`

This led to seeing the error messages
```
14:15:54 [tryorama] error: Test error: "TypeError: Cannot read properties of null (reading 'satisfies')\n" +
  '    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:353:25\n' +
  '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
  '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)'
not ok 42 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
          at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
          at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
          at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ...
14:15:54 [tryorama] debug: Test failed: flow records and relationships TypeError: Cannot read properties of null (reading 'satisfies')
    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:353:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  [stack]: "TypeError: Cannot read properties of null (reading 'satisfies')\n" +
    '    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:353:25\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)',
  [message]: "Cannot read properties of null (reading 'satisfies')"
}
```

**Comment by Connoropolous** [comment]
Putting it through `faucet` produces this... 

```
WASM_LOG=debug RUST_LOG="debug,wasmer_compiler_cranelift=error,holochain::core::workflow=error," RUST_BACKTRACE=1 GRAPHQL_DEBUG=1 npx tape --ignore .skip_tests flows/flow_records_graphql.js | npx faucet
# flow records and relationships
  ok 28 input commitment satisfaction created OKGraphQL query error Error: Cannot return null for non-nullable field Satisfaction.satisfiedBy.
    at completeValue (/Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/execution/execute.js:559:13)
    at /Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/execution/execute.js:469:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async Promise.all (index 5)
    at /Users/connor/code/hrea/test/init.js:68:20
    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:270:10
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  locations: [ { line: 50, column: 7 } ],
  path: [ 'ics', 'satisfiedBy' ]
}
GraphQL query error Error: Cannot return null for non-nullable field Satisfaction.satisfiedBy.
    at completeValue (/Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/execution/execute.js:559:13)
    at /Users/connor/code/hrea/node_modules/.pnpm/graphql@15.8.0/node_modules/graphql/execution/execute.js:469:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async Promise.all (index 4)
    at /Users/connor/code/hrea/test/init.js:68:20
    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:270:10
    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
  locations: [ { line: 37, column: 7 } ],
  path: [ 'ies', 'satisfiedBy' ]
⨯ flow records and relationships
  not ok 42 Test threw an exception. See output for details.
    ---
      operator: fail
      at: <anonymous> (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
      stack: |-
        Error: Test threw an exception. See output for details.
            at Test.assert [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:275:54)
            at Test.bound [as _assert] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
            at Test.fail (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:368:10)
            at Test.bound [as fail] (/Users/connor/code/hrea/node_modules/.pnpm/tape@4.15.0/node_modules/tape/lib/test.js:89:32)
            at /Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:137:13
            at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ...
  15:11:48 [tryorama] debug: Test failed: flow records and relationships TypeError: Cannot read properties of null (reading 'satisfies')
      at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:352:25
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29) {
    [stack]: "TypeError: Cannot read properties of null (reading 'satisfies')\n" +
      '    at /Users/connor/code/hrea/test/flows/flow_records_graphql.js:352:25\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at p (/Users/connor/code/hrea/node_modules/.pnpm/@holochain+tryorama@0.4.10/node_modules/@holochain/tryorama/src/middleware.ts:126:29)',
    [message]: "Cannot read properties of null (reading 'satisfies')"
  }
  15:11:48 [tryorama] debug: Cleaning up test: flow records and relationships
  15:11:48 [tryorama] debug: Calling Api._cleanup. description: flow records and relationships
  15:11:48 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
  15:11:48 [tryorama: player c0] debug: Shutting down...
  15:11:48 [tryorama: tryorama conductor c0] debug: Killing...
  15:11:48 [tryorama] info: conductor 'c0' exited with code null
  15:11:48 [tryorama: player c0] debug: Shut down.
  FIXME: ignoring onLeave
  15:11:48 [tryorama] debug: Finished with test: flow records and relationships

# tests 42
# pass  41
⨯ fail  1
```

It appears that suddenly after a failure it stops swallowing logs? I can't figure out the exact behaviour. The actual stack trace is the same, but it also reveals the useful stack trace

**Comment by Connoropolous** [comment]
It's happening like this because tryorama middleware is messing with the caught error
https://github.com/holochain/tryorama/blob/4b7d7d9a4d18e097706c275a004d8db9200f9c70/src/middleware.ts#L132-L139

**Comment by Connoropolous** [comment]
There is work on a new version of tryorama coming down, maybe early next week. 
https://github.com/holochain/tryorama/pull/108
